//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoDeUsuarios.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestaoDeUsuarios.Shared.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração realizada com sucesso.
        /// </summary>
        public static string AlteracaoRealizadaComSucesso {
            get {
                return ResourceManager.GetString("AlteracaoRealizadaComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro realizado com sucesso.
        /// </summary>
        public static string CadastroRealizadoComSucesso {
            get {
                return ResourceManager.GetString("CadastroRealizadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF Inválido.
        /// </summary>
        public static string CPFInvalido {
            get {
                return ResourceManager.GetString("CPFInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao alterar os dados.
        /// </summary>
        public static string FalhaAoAlterarDados {
            get {
                return ResourceManager.GetString("FalhaAoAlterarDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome inválido.
        /// </summary>
        public static string NomeInvalido {
            get {
                return ResourceManager.GetString("NomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome.
        /// </summary>
        public static string Sobrenome {
            get {
                return ResourceManager.GetString("Sobrenome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome inválido.
        /// </summary>
        public static string SobrenomeInvalido {
            get {
                return ResourceManager.GetString("SobrenomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string Telefone {
            get {
                return ResourceManager.GetString("Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone inválido.
        /// </summary>
        public static string TelefoneInvalido {
            get {
                return ResourceManager.GetString("TelefoneInvalido", resourceCulture);
            }
        }
    }
}
